const APP_VERSION = '3.0 Final';
const STORE_KEY = 'meteora_order_3_state';
const DEFAULT_PIN = '1234';
const app = document.getElementById('app');
const modal = document.getElementById('modal');
const modalContent = document.getElementById('modalContent');
const importFile = document.getElementById('importFile');
let view = 'tables';
let currentTableId = null;
let adminUnlocked = false;
let undoStack = [];
let redoStack = [];

const defaults = () => ({
  restaurantName:'Restaurant Meteora', pin:DEFAULT_PIN, lastSave:null,
  tables:Array.from({length:20},(_,i)=>({id:uid(), name:`Tisch ${i+1}`, guests:0, mergedWith:null, order:[]})),
  groups:[
    {id:'food',name:'Speisen',order:1},{id:'drinks',name:'Getränke',order:2}
  ],
  subgroups:[
    {id:'vorspeisen',groupId:'food',name:'Vorspeisen',order:1},{id:'salate',groupId:'food',name:'Salate',order:2},{id:'grill',groupId:'food',name:'Grillgerichte',order:3},{id:'fisch',groupId:'food',name:'Fisch',order:4},{id:'dessert',groupId:'food',name:'Dessert',order:5},
    {id:'alkoholfrei',groupId:'drinks',name:'Alkoholfrei',order:1},{id:'bier',groupId:'drinks',name:'Bier',order:2},{id:'wein',groupId:'drinks',name:'Wein',order:3},{id:'ouzo',groupId:'drinks',name:'Ouzo',order:4},{id:'schnaps',groupId:'drinks',name:'Schnaps',order:5},{id:'kaffee',groupId:'drinks',name:'Kaffee',order:6}
  ],
  items:[
    item('Cola 0,4','alkoholfrei'), item('Fanta 0,4','alkoholfrei'), item('Wasser 0,75','alkoholfrei'), item('Pils 0,5','bier'), item('Weizen 0,5','bier'), item('Ouzo','ouzo'), item('Espresso','kaffee'),
    item('Tzatziki','vorspeisen'), item('Bauernsalat','salate'), item('Gyros','grill'), item('Souvlaki','grill'), item('Calamari','fisch'), item('Galaktoboureko','dessert')
  ],
  quickNotes:['ohne Zwiebeln','extra scharf','ohne Knoblauch','Soße separat','kleine Portion']
});
function item(name, subgroupId){ return {id:uid(), name, subgroupId, active:true, order:Date.now()+Math.random()}; }
function uid(){ return 'id_'+Math.random().toString(36).slice(2,10)+'_'+Date.now().toString(36); }
let state = load();
function load(){ try{ const raw=localStorage.getItem(STORE_KEY); return raw? sanitize(JSON.parse(raw)) : defaults(); }catch(e){ return defaults(); }}
function sanitize(s){ const d=defaults(); s={...d,...s}; s.tables=Array.isArray(s.tables)?s.tables:d.tables; s.groups=Array.isArray(s.groups)?s.groups:d.groups; s.subgroups=Array.isArray(s.subgroups)?s.subgroups:d.subgroups; s.items=Array.isArray(s.items)?s.items:d.items; s.quickNotes=Array.isArray(s.quickNotes)?s.quickNotes:d.quickNotes; s.tables.forEach(t=>{ if(!Array.isArray(t.order)) t.order=[]; }); return s; }
function save(){ state.lastSave = new Date().toISOString(); localStorage.setItem(STORE_KEY, JSON.stringify(state)); document.getElementById('saveStatus').textContent='Gespeichert '+new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}); }
function money(n){ return Number(n||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'; }
function currentTable(){ return state.tables.find(t=>t.id===currentTableId) || state.tables[0]; }
function isBusy(t){ return t.order && t.order.length>0; }
function setView(v){ view=v; document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v)); render(); }
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{ if(b.dataset.view==='admin'&&!adminUnlocked) return askPin('admin'); if(b.dataset.view==='system'&&!adminUnlocked) return askPin('system'); setView(b.dataset.view); });

function render(){ document.getElementById('restaurantName').textContent=state.restaurantName; if(view==='tables') renderTables(); if(view==='order') renderOrder(); if(view==='admin') renderAdmin(); if(view==='system') renderSystem(); }
function renderTables(){ app.innerHTML=`<div class="between card"><div><div class="big">Tische</div><p>${state.tables.length} Tische · ${state.tables.filter(isBusy).length} besetzt</p></div><button class="primary" onclick="openTableEditor()">+ Tisch</button></div><div class="grid tables-grid">${state.tables.map(t=>`<button class="table-card ${isBusy(t)?'busy':'free'}" onclick="openTable('${t.id}')"><div class="between"><b>${esc(t.name)}</b><span class="badge ${isBusy(t)?'busy':'free'}">${isBusy(t)?'🔴 Besetzt':'🟢 Frei'}</span></div><p>Gäste: ${t.guests||0}</p><p>${(t.order||[]).reduce((a,l)=>a+l.qty,0)} Positionen</p></button>`).join('')}</div>`; }
function openTable(id){ currentTableId=id; view='order'; document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',false)); render(); }
let selectedGroup='', selectedSubgroup='', search='';
function renderOrder(){ const t=currentTable(); selectedGroup ||= state.groups.sort(byOrder)[0]?.id || ''; const subs=state.subgroups.filter(s=>s.groupId===selectedGroup).sort(byOrder); selectedSubgroup ||= subs[0]?.id || ''; const q=search.toLowerCase().trim(); const items=state.items.filter(i=>i.active!==false).filter(i=>!selectedSubgroup||i.subgroupId===selectedSubgroup).filter(i=>!q || i.name.toLowerCase().includes(q) || subgroupName(i.subgroupId).toLowerCase().includes(q) || groupName(groupOfSub(i.subgroupId)).toLowerCase().includes(q)).sort(byOrder);
app.innerHTML=`<div class="between card"><div><button class="ghost" onclick="setView('tables')">← Tische</button><span class="big"> ${esc(t.name)}</span><p>👥 Gäste: <button class="small" onclick="setGuests(-1)">−</button> ${t.guests||0} <button class="small" onclick="setGuests(1)">+</button> · ${isBusy(t)?'🔴 Besetzt':'🟢 Frei'}</p></div><div class="row"><button class="warn" onclick="mergeTables()">Zusammenlegen</button><button class="ghost" onclick="splitTable()">Trennen</button></div></div><div class="split"><section><div class="card"><input class="input" placeholder="Artikel suchen…" value="${esc(search)}" oninput="search=this.value; renderOrder()"><div class="tabs" style="margin-top:10px">${state.groups.sort(byOrder).map(g=>`<button class="chip ${selectedGroup===g.id?'active':''}" onclick="selectedGroup='${g.id}'; selectedSubgroup=''; search=''; renderOrder()">${esc(g.name)}</button>`).join('')}</div><div class="tabs">${subs.map(s=>`<button class="chip ${selectedSubgroup===s.id?'active':''}" onclick="selectedSubgroup='${s.id}'; renderOrder()">${esc(s.name)}</button>`).join('')}</div><div class="row"><button class="ghost small" onclick="search=''; selectedSubgroup=''; renderOrder()">Filter zurücksetzen</button><button class="primary small" onclick="openOther()">+ Sonstiges</button></div></div><div class="items">${items.map(i=>`<button class="item" onclick="addItem('${i.id}')"><b>${esc(i.name)}</b><p>${esc(subgroupName(i.subgroupId))}</p></button>`).join('') || '<div class="empty">Keine Artikel gefunden.</div>'}</div></section><aside><div class="card"><div class="between"><div><div class="big">Bestellung</div><p>${(t.order||[]).reduce((a,l)=>a+l.qty,0)} Artikel</p></div><button class="danger" onclick="clearTable()">Tisch leeren</button></div></div>${(t.order||[]).length?t.order.map(l=>orderLine(l)).join(''):'<div class="empty">Noch keine Bestellung.</div>'}<div class="card row"><button class="warn" onclick="undoLast()">↩ Letzte zurück</button><button class="ghost" onclick="restoreLast()">♻ Wiederherstellen</button><button class="primary" onclick="copyOrder()">Bestellung kopieren</button></div></aside></div>`; }
function orderLine(l){ return `<div class="order-line"><div><b>${esc(l.name)}</b>${l.note?`<p>📝 ${esc(l.note)}</p>`:''}<div class="row">${state.quickNotes.map(n=>`<button class="small ghost" onclick="setNote('${l.id}','${enc(n)}')">${esc(n)}</button>`).join('')}<button class="small ghost" onclick="editNote('${l.id}')">Bemerkung</button></div></div><div class="qty"><button onclick="changeQty('${l.id}',-1)">−</button><b>${l.qty}</b><button onclick="changeQty('${l.id}',1)">+</button></div></div>`; }
function addItem(id){ const i=state.items.find(x=>x.id===id); if(!i) return; addOrderLine({name:i.name,itemId:i.id,subgroupId:i.subgroupId,qty:1,note:''}); }
function addOrderLine(line){ const t=currentTable(); const existing=t.order.find(l=>l.itemId===line.itemId && l.note===(line.note||'') && l.name===line.name); pushUndo(); if(existing) existing.qty+=line.qty; else t.order.push({id:uid(),...line}); save(); renderOrder(); }
function changeQty(id,delta){ const t=currentTable(); const l=t.order.find(x=>x.id===id); if(!l) return; pushUndo(); l.qty+=delta; if(l.qty<=0) t.order=t.order.filter(x=>x.id!==id); save(); renderOrder(); }
function setGuests(delta){ const t=currentTable(); t.guests=Math.max(0,(t.guests||0)+delta); save(); renderOrder(); }
function pushUndo(){ undoStack.push(JSON.stringify(state.tables)); if(undoStack.length>20) undoStack.shift(); redoStack=[]; }
function undoLast(){ if(!undoStack.length) return alert('Keine Aktion zum Rückgängig machen.'); redoStack.push(JSON.stringify(state.tables)); state.tables=JSON.parse(undoStack.pop()); save(); render(); }
function restoreLast(){ if(!redoStack.length) return alert('Keine Wiederherstellung vorhanden.'); undoStack.push(JSON.stringify(state.tables)); state.tables=JSON.parse(redoStack.pop()); save(); render(); }
function editNote(id){ const t=currentTable(); const l=t.order.find(x=>x.id===id); if(!l)return; promptModal('Bemerkung',`<textarea id="mNote">${esc(l.note||'')}</textarea>`,()=>{ l.note=document.getElementById('mNote').value.trim(); save(); renderOrder(); }); }
function setNote(id,n){ const t=currentTable(); const l=t.order.find(x=>x.id===id); if(l){ l.note=dec(n); save(); renderOrder(); }}
function openOther(){ promptModal('Sonstiges hinzufügen',`<label>Bezeichnung<input id="mName" placeholder="z. B. Extra Brot"></label><label>Menge<input id="mQty" type="number" min="1" value="1"></label><label>Bemerkung<textarea id="mNote"></textarea></label>`,()=>{ const name=document.getElementById('mName').value.trim(); if(!name) return alert('Bitte Bezeichnung eingeben.'); addOrderLine({name:'Sonstiges: '+name,itemId:'other_'+name.toLowerCase(),subgroupId:'other',qty:Math.max(1,parseInt(document.getElementById('mQty').value||'1')),note:document.getElementById('mNote').value.trim()}); }); }
function clearTable(){ const t=currentTable(); if(!t.order.length) return; if(confirm(`${t.name} wirklich leeren?`)){ pushUndo(); t.order=[]; t.guests=0; t.mergedWith=null; save(); renderOrder(); }}
function copyOrder(){ const t=currentTable(); const txt=`${state.restaurantName}\n${t.name}\n\n`+(t.order||[]).map(l=>`${l.qty}× ${l.name}${l.note?' - '+l.note:''}`).join('\n'); navigator.clipboard?.writeText(txt); alert(txt); }
function mergeTables(){ const t=currentTable(); const target=prompt('Mit welchem Tisch zusammenlegen? Name eingeben:'); if(!target) return; const other=state.tables.find(x=>x.name.toLowerCase()===target.toLowerCase()&&x.id!==t.id); if(!other) return alert('Tisch nicht gefunden.'); pushUndo(); other.order.forEach(l=>addOrderLineTo(t,l)); other.order=[]; other.guests=0; t.guests=(t.guests||0)+(other.guests||0); t.mergedWith=other.name; save(); renderOrder(); }
function addOrderLineTo(t,l){ const ex=t.order.find(x=>x.itemId===l.itemId&&x.note===l.note&&x.name===l.name); if(ex) ex.qty+=l.qty; else t.order.push({...l,id:uid()}); }
function splitTable(){ const t=currentTable(); t.mergedWith=null; save(); renderOrder(); }

function renderAdmin(){ app.innerHTML=`<div class="between card"><div><div class="big">Admin</div><p>PIN-geschützt · Version ${APP_VERSION}</p></div><button class="ghost" onclick="adminUnlocked=false; setView('tables')">Sperren</button></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr))"><div class="card"><h3>Tische</h3><button class="primary" onclick="openTableEditor()">+ Tisch</button><div class="admin-list">${state.tables.map(t=>`<div class="admin-row"><span>${esc(t.name)}</span><div><button class="small" onclick="openTableEditor('${t.id}')">Bearb.</button><button class="small danger" onclick="deleteTable('${t.id}')">Löschen</button></div></div>`).join('')}</div></div><div class="card"><h3>Gruppen</h3><button class="primary" onclick="editGroup()">+ Hauptgruppe</button>${state.groups.sort(byOrder).map(g=>`<div class="admin-row"><span>${esc(g.name)}</span><div><button class="small" onclick="editGroup('${g.id}')">Bearb.</button><button class="small danger" onclick="deleteGroup('${g.id}')">Löschen</button></div></div>`).join('')}</div><div class="card"><h3>Untergruppen</h3><button class="primary" onclick="editSubgroup()">+ Untergruppe</button>${state.subgroups.sort((a,b)=>groupName(a.groupId).localeCompare(groupName(b.groupId))||byOrder(a,b)).map(s=>`<div class="admin-row"><span>${esc(groupName(s.groupId))} › ${esc(s.name)}</span><div><button class="small" onclick="editSubgroup('${s.id}')">Bearb.</button><button class="small danger" onclick="deleteSubgroup('${s.id}')">Löschen</button></div></div>`).join('')}</div><div class="card"><h3>Artikel</h3><button class="primary" onclick="editItem()">+ Artikel</button>${state.items.sort((a,b)=>subgroupName(a.subgroupId).localeCompare(subgroupName(b.subgroupId))||a.name.localeCompare(b.name)).map(i=>`<div class="admin-row"><span>${i.active===false?'🚫 ':' '}${esc(subgroupName(i.subgroupId))} › ${esc(i.name)}</span><div><button class="small" onclick="editItem('${i.id}')">Bearb.</button><button class="small danger" onclick="deleteItem('${i.id}')">Löschen</button></div></div>`).join('')}</div><div class="card"><h3>Einstellungen</h3><label>Restaurantname<input value="${esc(state.restaurantName)}" onchange="state.restaurantName=this.value; save(); render()"></label><button class="warn" onclick="changePin()">PIN ändern</button><h4>Schnell-Bemerkungen</h4><textarea onchange="state.quickNotes=this.value.split('\n').map(x=>x.trim()).filter(Boolean); save()">${esc(state.quickNotes.join('\n'))}</textarea></div></div>`; }
function askPin(target){ const pin=prompt('Admin-PIN eingeben:'); if(pin===state.pin){ adminUnlocked=true; setView(target); } else if(pin!==null) alert('Falsche PIN.'); }
function openTableEditor(id){ const t=state.tables.find(x=>x.id===id)||{name:'',guests:0}; promptModal(id?'Tisch bearbeiten':'Tisch anlegen',`<label>Name<input id="mName" value="${esc(t.name)}"></label>`,()=>{ const name=document.getElementById('mName').value.trim(); if(!name)return; if(id)t.name=name; else state.tables.push({id:uid(),name,guests:0,mergedWith:null,order:[]}); save(); render(); }); }
function deleteTable(id){ const t=state.tables.find(x=>x.id===id); if(t?.order?.length) return alert('Tisch erst leeren.'); if(confirm('Tisch löschen?')){ state.tables=state.tables.filter(x=>x.id!==id); save(); renderAdmin(); }}
function editGroup(id){ const g=state.groups.find(x=>x.id===id)||{name:'',order:state.groups.length+1}; promptModal(id?'Hauptgruppe bearbeiten':'Hauptgruppe anlegen',`<input id="mName" value="${esc(g.name)}" placeholder="Name"><input id="mOrder" type="number" value="${g.order||1}" placeholder="Reihenfolge">`,()=>{ const name=mName.value.trim(); if(!name)return; if(id){g.name=name;g.order=+mOrder.value||1}else state.groups.push({id:uid(),name,order:+mOrder.value||1}); save(); renderAdmin(); }); }
function deleteGroup(id){ if(state.subgroups.some(s=>s.groupId===id)) return alert('Erst Untergruppen löschen.'); state.groups=state.groups.filter(g=>g.id!==id); save(); renderAdmin(); }
function editSubgroup(id){ const s=state.subgroups.find(x=>x.id===id)||{name:'',groupId:state.groups[0]?.id,order:state.subgroups.length+1}; promptModal(id?'Untergruppe bearbeiten':'Untergruppe anlegen',`<input id="mName" value="${esc(s.name)}" placeholder="Name"><select id="mGroup">${state.groups.map(g=>`<option value="${g.id}" ${s.groupId===g.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select><input id="mOrder" type="number" value="${s.order||1}">`,()=>{ const name=mName.value.trim(); if(!name)return; if(id){s.name=name;s.groupId=mGroup.value;s.order=+mOrder.value||1}else state.subgroups.push({id:uid(),name,groupId:mGroup.value,order:+mOrder.value||1}); save(); renderAdmin(); }); }
function deleteSubgroup(id){ if(state.items.some(i=>i.subgroupId===id)) return alert('Erst Artikel löschen/verschieben.'); state.subgroups=state.subgroups.filter(s=>s.id!==id); save(); renderAdmin(); }
function editItem(id){ const i=state.items.find(x=>x.id===id)||{name:'',subgroupId:state.subgroups[0]?.id,active:true,order:state.items.length+1}; promptModal(id?'Artikel bearbeiten':'Artikel anlegen',`<input id="mName" value="${esc(i.name)}" placeholder="Name"><select id="mSub">${state.subgroups.map(s=>`<option value="${s.id}" ${i.subgroupId===s.id?'selected':''}>${esc(groupName(s.groupId))} › ${esc(s.name)}</option>`).join('')}</select><input id="mOrder" type="number" value="${i.order||1}"><label><input id="mActive" type="checkbox" ${i.active!==false?'checked':''}> Aktiv</label>`,()=>{ const name=mName.value.trim(); if(!name)return; if(id){i.name=name;i.subgroupId=mSub.value;i.order=+mOrder.value||1;i.active=mActive.checked}else state.items.push({id:uid(),name,subgroupId:mSub.value,order:+mOrder.value||1,active:mActive.checked}); save(); renderAdmin(); }); }
function deleteItem(id){ if(confirm('Artikel löschen?')){ state.items=state.items.filter(i=>i.id!==id); save(); renderAdmin(); }}
function changePin(){ const p=prompt('Neue PIN:'); if(p&&p.length>=4){ state.pin=p; save(); alert('PIN geändert.'); }}

function renderSystem(){ app.innerHTML=`<div class="card"><div class="big">System</div><p>Meteora Order ${APP_VERSION} · Lokale Daten pro Gerät · kein Cloud-Abgleich</p></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(220px,1fr))"><button class="primary" onclick="exportBackup()">Backup exportieren</button><button class="ghost" onclick="importFile.click()">Backup importieren</button><button class="warn" onclick="installPwa()">App installieren</button><button class="danger" onclick="resetData()">Daten zurücksetzen</button></div><div class="card"><h3>Info</h3><p>Restaurant: ${esc(state.restaurantName)}</p><p>Letzte Speicherung: ${state.lastSave?new Date(state.lastSave).toLocaleString('de-DE'):'—'}</p><p>Admin-PIN Standard: 1234</p></div>`; }
function exportBackup(){ const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); download(blob,`meteora-order-3-backup-${stamp()}.json`); }
importFile.onchange=async()=>{ const f=importFile.files[0]; if(!f)return; try{ const json=JSON.parse(await f.text()); if(!json.tables||!json.groups||!json.subgroups||!json.items) throw new Error('Format'); if(confirm('Backup importieren? Aktuelle Daten werden ersetzt.')){ state=sanitize(json); save(); setView('tables'); }}catch(e){ alert('Backup konnte nicht gelesen werden.'); } importFile.value=''; };
function resetData(){ const x=prompt('Zum Zurücksetzen LÖSCHEN eingeben:'); if(x==='LÖSCHEN'){ state=defaults(); undoStack=[]; redoStack=[]; save(); setView('tables'); }}
let deferredPrompt=null; window.addEventListener('beforeinstallprompt',e=>{ e.preventDefault(); deferredPrompt=e; }); function installPwa(){ if(deferredPrompt){ deferredPrompt.prompt(); deferredPrompt=null; } else alert('Auf iPhone: Safari öffnen → Teilen → Zum Home-Bildschirm.'); }
if('serviceWorker' in navigator){ navigator.serviceWorker.register('service-worker.js').catch(()=>{}); }

function promptModal(title,html,onOk){ modalContent.innerHTML=`<h2>${title}</h2><div class="grid">${html}</div><div class="modal-actions"><button value="cancel" class="ghost">Abbrechen</button><button id="okBtn" value="default" class="primary">Speichern</button></div>`; modal.showModal(); document.getElementById('okBtn').onclick=(e)=>{e.preventDefault(); onOk(); modal.close();}; }
function groupName(id){ return state.groups.find(g=>g.id===id)?.name||'Gruppe'; } function subgroupName(id){ return state.subgroups.find(s=>s.id===id)?.name||'Sonstiges'; } function groupOfSub(id){ return state.subgroups.find(s=>s.id===id)?.groupId||''; } function byOrder(a,b){ return (a.order||0)-(b.order||0)||String(a.name).localeCompare(String(b.name)); }
function esc(s){ return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); } function enc(s){return encodeURIComponent(s)} function dec(s){return decodeURIComponent(s)} function stamp(){ return new Date().toISOString().slice(0,19).replace(/[T:]/g,'-'); } function download(blob,name){ const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
render();
